name: Node.js Unit Tests

on:
  pull_request:
    branches: [main]
    paths:
      - 'hello-world-node/**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        working-directory: ./hello-world-node
        run: |
          npm install
          npm install mocha nyc chai --save-dev
          
      - name: Run tests
        working-directory: ./hello-world-node
        run: npm test

      - name: Upload coverage # TODO: No files were found with the provided path: hello-world-node/coverage. No artifacts will be uploaded.
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: hello-world-node/coverage